deployments:
  environment: production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2UwYmIyNGViLTA2ZWEtNDAwZC1hYmI5LTI4ZTAxZmFmYWU1Mi9mMDc2YTRiMi0zODUwLTExZWUtOTg1NS0wYWJlM2Y0YTY2MDE=
