name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy to staging
        env:
          ENVIRONMENT: staging
        run: |
          echo "Building and deploying to staging..."
          # Add your build and deployment commands for staging environment here

      - name: Build and deploy to production
        env:
          ENVIRONMENT: production
        run: |
          echo "Building and deploying to production..."
          # Add your build and deployment commands for production environment here
